"""zme

Revision ID: 1413b0e217b1
Revises: 9c1894d732f3
Create Date: 2026-03-04 07:25:04.682398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1413b0e217b1'
down_revision: Union[str, Sequence[str], None] = '9c1894d732f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zme',
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('active_bid', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zme_active_bid'), 'zme', ['active_bid'], unique=False)
    op.create_index(op.f('ix_zme_biz_id'), 'zme', ['biz_id'], unique=False)
    op.create_index(op.f('ix_zme_created_by'), 'zme', ['created_by'], unique=False)
    op.create_index(op.f('ix_zme_firebase_uid'), 'zme', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_zme_id'), 'zme', ['id'], unique=False)
    op.create_index(op.f('ix_zme_owner_id'), 'zme', ['owner_id'], unique=False)
    op.create_index(op.f('ix_zme_ten_id'), 'zme', ['ten_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zme_ten_id'), table_name='zme')
    op.drop_index(op.f('ix_zme_owner_id'), table_name='zme')
    op.drop_index(op.f('ix_zme_id'), table_name='zme')
    op.drop_index(op.f('ix_zme_firebase_uid'), table_name='zme')
    op.drop_index(op.f('ix_zme_created_by'), table_name='zme')
    op.drop_index(op.f('ix_zme_biz_id'), table_name='zme')
    op.drop_index(op.f('ix_zme_active_bid'), table_name='zme')
    op.drop_table('zme')
    # ### end Alembic commands ###
