"""semi1

Revision ID: 15f5dc556088
Revises: 7b12e6d64aeb
Create Date: 2026-03-12 00:45:40.119401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f5dc556088'
down_revision: Union[str, Sequence[str], None] = '7b12e6d64aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_schedules', sa.Column('semi1', sa.String(), nullable=True))
    op.add_column('payroll_schedules', sa.Column('semi2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_schedules', 'semi2')
    op.drop_column('payroll_schedules', 'semi1')
    # ### end Alembic commands ###
