"""period

Revision ID: 1883ba7cb3e0
Revises: 36f6f88b9e37
Create Date: 2026-02-17 20:08:52.930096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1883ba7cb3e0'
down_revision: Union[str, Sequence[str], None] = '36f6f88b9e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payroll_entries', 'payroll_period_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('payroll_entries', 'employee_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('payroll_entries', 'regular_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('payroll_entries', 'hourly_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('payroll_entries', 'overtime_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('payroll_entries', 'overtime_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('payroll_entries', 'bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('payroll_entries', 'vacation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('payroll_entries', 'cpp',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('payroll_entries', 'ei',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('payroll_entries', 'tax',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('payroll_entries', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payroll_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('payroll_periods', sa.Column('pay_date', sa.Date(), nullable=False))
    op.add_column('payroll_periods', sa.Column('fiscal_year', sa.Integer(), nullable=False))
    op.add_column('payroll_periods', sa.Column('period_number', sa.Integer(), nullable=False))
    op.add_column('payroll_periods', sa.Column('frequency', sa.String(), nullable=False))
    op.alter_column('payroll_periods', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('payroll_periods', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('payroll_periods', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payroll_periods', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payroll_periods', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payroll_periods', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payroll_periods', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('payroll_periods', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('payroll_periods', 'frequency')
    op.drop_column('payroll_periods', 'period_number')
    op.drop_column('payroll_periods', 'fiscal_year')
    op.drop_column('payroll_periods', 'pay_date')
    op.alter_column('payroll_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payroll_entries', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payroll_entries', 'tax',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('payroll_entries', 'ei',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('payroll_entries', 'cpp',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('payroll_entries', 'vacation',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('payroll_entries', 'bonus',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('payroll_entries', 'overtime_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('payroll_entries', 'overtime_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('payroll_entries', 'hourly_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('payroll_entries', 'regular_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('payroll_entries', 'employee_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('payroll_entries', 'payroll_period_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
