"""e384

Revision ID: 19f015eaf82f
Revises: 3cad7e8dd7c7
Create Date: 2026-03-23 22:46:20.464822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '19f015eaf82f'
down_revision: Union[str, Sequence[str], None] = '3cad7e8dd7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_history_384', sa.Column('embedding', Vector(dim=384), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_history_384', 'embedding')
    # ### end Alembic commands ###
