"""my_tenant

Revision ID: 1e1e3cd3689d
Revises: 3f925462e264
Create Date: 2026-02-19 09:18:40.909415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e1e3cd3689d'
down_revision: Union[str, Sequence[str], None] = '3f925462e264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biz_entities',
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('business_number', sa.String(length=15), nullable=True),
    sa.Column('payroll_account_number', sa.String(length=15), nullable=True),
    sa.Column('province', sa.String(length=2), nullable=True),
    sa.Column('street_address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(length=7), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('wsib_number', sa.String(), nullable=True),
    sa.Column('eht_account', sa.String(), nullable=True),
    sa.Column('remittance_frequency', sa.String(), nullable=True),
    sa.Column('tax_year_end', sa.Date(), nullable=True),
    sa.Column('legal_name', sa.String(), nullable=True),
    sa.Column('operating_name', sa.String(), nullable=True),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biz_entities_biz_id'), 'biz_entities', ['biz_id'], unique=False)
    op.create_index(op.f('ix_biz_entities_id'), 'biz_entities', ['id'], unique=False)
    op.create_index(op.f('ix_biz_entities_ten_id'), 'biz_entities', ['ten_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_biz_entities_ten_id'), table_name='biz_entities')
    op.drop_index(op.f('ix_biz_entities_id'), table_name='biz_entities')
    op.drop_index(op.f('ix_biz_entities_biz_id'), table_name='biz_entities')
    op.drop_table('biz_entities')
    # ### end Alembic commands ###
