"""payroll

Revision ID: 2b5f2fc22bdb
Revises: 67354d5da945
Create Date: 2026-02-23 23:12:00.965892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b5f2fc22bdb'
down_revision: Union[str, Sequence[str], None] = '67354d5da945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('github', sa.String(), nullable=True),
    sa.Column('reddit', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pin', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('tax_no', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_biz_id'), 'users', ['biz_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_owner_id'), 'users', ['owner_id'], unique=False)
    op.create_index(op.f('ix_users_ten_id'), 'users', ['ten_id'], unique=False)
    op.create_table('z_user_ten',
    sa.Column('firebase_uid', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_z_user_ten_biz_id'), 'z_user_ten', ['biz_id'], unique=False)
    op.create_index(op.f('ix_z_user_ten_firebase_uid'), 'z_user_ten', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_z_user_ten_id'), 'z_user_ten', ['id'], unique=False)
    op.create_index(op.f('ix_z_user_ten_owner_id'), 'z_user_ten', ['owner_id'], unique=False)
    op.create_index(op.f('ix_z_user_ten_ten_id'), 'z_user_ten', ['ten_id'], unique=False)
    op.drop_index(op.f('ix_my_users_biz_id'), table_name='my_users')
    op.drop_index(op.f('ix_my_users_email'), table_name='my_users')
    op.drop_index(op.f('ix_my_users_firebase_uid'), table_name='my_users')
    op.drop_index(op.f('ix_my_users_id'), table_name='my_users')
    op.drop_index(op.f('ix_my_users_owner_id'), table_name='my_users')
    op.drop_index(op.f('ix_my_users_ten_id'), table_name='my_users')
    op.drop_table('my_users')
    op.drop_index(op.f('ix_my_tenants_biz_id'), table_name='my_tenants')
    op.drop_index(op.f('ix_my_tenants_id'), table_name='my_tenants')
    op.drop_index(op.f('ix_my_tenants_owner_id'), table_name='my_tenants')
    op.drop_index(op.f('ix_my_tenants_ten_id'), table_name='my_tenants')
    op.drop_table('my_tenants')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_tenants',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('b_int', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('b_str', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_decimal', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('b_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('b_bool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_flag', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('business_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('payroll_account_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('province', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('street_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wsib_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('eht_account', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('remittance_frequency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tax_year_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('legal_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('operating_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('business_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('incorporation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('employee_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ten_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('biz_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('organizations_pkey'))
    )
    op.create_index(op.f('ix_my_tenants_ten_id'), 'my_tenants', ['ten_id'], unique=False)
    op.create_index(op.f('ix_my_tenants_owner_id'), 'my_tenants', ['owner_id'], unique=False)
    op.create_index(op.f('ix_my_tenants_id'), 'my_tenants', ['id'], unique=False)
    op.create_index(op.f('ix_my_tenants_biz_id'), 'my_tenants', ['biz_id'], unique=False)
    op.create_table('my_users',
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('b_int', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('b_str', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_decimal', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('b_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('b_bool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_flag', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('firebase_uid', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ten_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('biz_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('facebook', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('twitter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('github', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reddit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tax_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_my_users_ten_id'), 'my_users', ['ten_id'], unique=False)
    op.create_index(op.f('ix_my_users_owner_id'), 'my_users', ['owner_id'], unique=False)
    op.create_index(op.f('ix_my_users_id'), 'my_users', ['id'], unique=False)
    op.create_index(op.f('ix_my_users_firebase_uid'), 'my_users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_my_users_email'), 'my_users', ['email'], unique=True)
    op.create_index(op.f('ix_my_users_biz_id'), 'my_users', ['biz_id'], unique=False)
    op.drop_index(op.f('ix_z_user_ten_ten_id'), table_name='z_user_ten')
    op.drop_index(op.f('ix_z_user_ten_owner_id'), table_name='z_user_ten')
    op.drop_index(op.f('ix_z_user_ten_id'), table_name='z_user_ten')
    op.drop_index(op.f('ix_z_user_ten_firebase_uid'), table_name='z_user_ten')
    op.drop_index(op.f('ix_z_user_ten_biz_id'), table_name='z_user_ten')
    op.drop_table('z_user_ten')
    op.drop_index(op.f('ix_users_ten_id'), table_name='users')
    op.drop_index(op.f('ix_users_owner_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_biz_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
