"""fullname

Revision ID: 2ce236c782ba
Revises: 653c5d65f38d
Create Date: 2026-03-14 19:34:29.719108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce236c782ba'
down_revision: Union[str, Sequence[str], None] = '653c5d65f38d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_history', sa.Column('excluded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_history', 'excluded')
    # ### end Alembic commands ###
