"""hrs perday

Revision ID: 307f850278c9
Revises: 7104aedbe160
Create Date: 2026-03-09 15:20:18.895848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307f850278c9'
down_revision: Union[str, Sequence[str], None] = '7104aedbe160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('hours_per_day', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('employees', sa.Column('days_per_week', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'days_per_week')
    op.drop_column('employees', 'hours_per_day')
    # ### end Alembic commands ###
