"""Add Canadian payroll fields to organizations

Revision ID: 335958e551b0
Revises: 87fa8e031ff1
Create Date: 2026-02-19 00:36:14.762399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '335958e551b0'
down_revision: Union[str, Sequence[str], None] = '87fa8e031ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('business_number', sa.String(length=15), nullable=True))
    op.add_column('organizations', sa.Column('payroll_account_number', sa.String(length=15), nullable=True))
    op.add_column('organizations', sa.Column('province', sa.String(length=2), nullable=True))
    op.add_column('organizations', sa.Column('street_address', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('city', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('postal_code', sa.String(length=7), nullable=True))
    op.add_column('organizations', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('email', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('wsib_number', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('eht_account', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('remittance_frequency', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('tax_year_end', sa.Date(), nullable=True))
    op.add_column('organizations', sa.Column('legal_name', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('operating_name', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('business_type', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('incorporation_date', sa.Date(), nullable=True))
    op.add_column('organizations', sa.Column('employee_count', sa.Integer(), nullable=True))
    op.alter_column('payroll_periods', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payroll_periods', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('organizations', 'employee_count')
    op.drop_column('organizations', 'incorporation_date')
    op.drop_column('organizations', 'business_type')
    op.drop_column('organizations', 'operating_name')
    op.drop_column('organizations', 'legal_name')
    op.drop_column('organizations', 'tax_year_end')
    op.drop_column('organizations', 'remittance_frequency')
    op.drop_column('organizations', 'eht_account')
    op.drop_column('organizations', 'wsib_number')
    op.drop_column('organizations', 'email')
    op.drop_column('organizations', 'phone')
    op.drop_column('organizations', 'postal_code')
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'street_address')
    op.drop_column('organizations', 'province')
    op.drop_column('organizations', 'payroll_account_number')
    op.drop_column('organizations', 'business_number')
    # ### end Alembic commands ###
