"""zme

Revision ID: 34b45438832c
Revises: 82e970ebeca5
Create Date: 2026-03-08 01:13:04.447138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b45438832c'
down_revision: Union[str, Sequence[str], None] = '82e970ebeca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zme_active_bid'), table_name='zme')
    op.drop_column('zme', 'active_bid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zme', sa.Column('active_bid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_zme_active_bid'), 'zme', ['active_bid'], unique=False)
    # ### end Alembic commands ###
