"""payroll

Revision ID: 36f6f88b9e37
Revises: a632e92064a9
Create Date: 2026-02-16 23:42:12.727646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f6f88b9e37'
down_revision: Union[str, Sequence[str], None] = 'a632e92064a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payroll_entries', 'gross',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.alter_column('payroll_entries', 'total_deduction',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.alter_column('payroll_entries', 'net',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payroll_entries', 'net',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    op.alter_column('payroll_entries', 'total_deduction',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    op.alter_column('payroll_entries', 'gross',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    # ### end Alembic commands ###
