"""gin

Revision ID: 377fcaa8f830
Revises: 5ed5bfda48fb
Create Date: 2026-03-24 17:24:29.016552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377fcaa8f830'
down_revision: Union[str, Sequence[str], None] = '5ed5bfda48fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_history_384', sa.Column('text_score', sa.Numeric(precision=10, scale=6), nullable=True))
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', postgresql_using='gin')
    op.drop_column('payroll_history_384', 'text_score')
    # ### end Alembic commands ###
