"""payroll

Revision ID: 3acde0fb9b24
Revises: 461599cb2031
Create Date: 2026-02-20 20:52:58.391750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3acde0fb9b24'
down_revision: Union[str, Sequence[str], None] = '461599cb2031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_users', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_users', 'icon')
    # ### end Alembic commands ###
