"""e384

Revision ID: 3cad7e8dd7c7
Revises: b550f72b5b23
Create Date: 2026-03-23 22:42:49.792289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision: str = '3cad7e8dd7c7'
down_revision: Union[str, Sequence[str], None] = 'b550f72b5b23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_history_384',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('chunk', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_history_384_id'), 'payroll_history_384', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_history_384_id'), table_name='payroll_history_384')
    op.drop_table('payroll_history_384')
    # ### end Alembic commands ###
