"""hrs 

Revision ID: 3ce6395aa1d4
Revises: 830578af0d09
Create Date: 2026-03-12 18:15:17.102950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce6395aa1d4'
down_revision: Union[str, Sequence[str], None] = '830578af0d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('regular_hours', sa.Numeric(precision=5, scale=2), nullable=True))
    op.drop_constraint(op.f('employees_biz_id_fkey'), 'employees', type_='foreignkey')
    op.drop_column('employees', 'days_per_week')
    op.drop_column('employees', 'hours_per_day')
    op.add_column('payroll_entries', sa.Column('schedule_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_payroll_entries_payroll_period_id'), table_name='payroll_entries')
    op.drop_constraint(op.f('uq_period_employee'), 'payroll_entries', type_='unique')
    op.create_index(op.f('ix_payroll_entries_schedule_id'), 'payroll_entries', ['schedule_id'], unique=False)
    op.create_unique_constraint('uq_schedule_employee', 'payroll_entries', ['schedule_id', 'employee_id'])
    op.create_foreign_key(None, 'payroll_entries', 'payroll_schedules', ['schedule_id'], ['id'])
    op.drop_column('payroll_entries', 'payroll_period_id')
    op.alter_column('payroll_schedules', 'frequency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payroll_schedules', 'period',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payroll_schedules', 'note',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payroll_schedules', 'effective_from',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('payroll_schedules', 'effective_to',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('payroll_schedules', 'payon',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payroll_schedules', 'semi1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payroll_schedules', 'semi2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payroll_schedules', 'semi2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payroll_schedules', 'semi1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payroll_schedules', 'payon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payroll_schedules', 'effective_to',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('payroll_schedules', 'effective_from',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('payroll_schedules', 'note',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payroll_schedules', 'period',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payroll_schedules', 'frequency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('payroll_entries', sa.Column('payroll_period_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payroll_entries', type_='foreignkey')
    op.drop_constraint('uq_schedule_employee', 'payroll_entries', type_='unique')
    op.drop_index(op.f('ix_payroll_entries_schedule_id'), table_name='payroll_entries')
    op.create_unique_constraint(op.f('uq_period_employee'), 'payroll_entries', ['payroll_period_id', 'employee_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_payroll_entries_payroll_period_id'), 'payroll_entries', ['payroll_period_id'], unique=False)
    op.drop_column('payroll_entries', 'schedule_id')
    op.add_column('employees', sa.Column('hours_per_day', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('days_per_week', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('employees_biz_id_fkey'), 'employees', 'biz_entities', ['biz_id'], ['id'])
    op.drop_column('employees', 'regular_hours')
    # ### end Alembic commands ###
