"""my_tenant

Revision ID: 3f925462e264
Revises: 3c2be954ebc0
Create Date: 2026-02-19 09:16:27.094304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f925462e264'
down_revision: Union[str, Sequence[str], None] = '3c2be954ebc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cra_submissions', sa.Column('ten_id', sa.Uuid(), nullable=True))
    op.add_column('cra_submissions', sa.Column('biz_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_cra_submissions_org_id'), table_name='cra_submissions')
    op.create_index(op.f('ix_cra_submissions_biz_id'), 'cra_submissions', ['biz_id'], unique=False)
    op.create_index(op.f('ix_cra_submissions_ten_id'), 'cra_submissions', ['ten_id'], unique=False)
    op.drop_column('cra_submissions', 'org_id')
    op.add_column('employees', sa.Column('ten_id', sa.Uuid(), nullable=True))
    op.add_column('employees', sa.Column('biz_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_employees_org_id'), table_name='employees')
    op.create_index(op.f('ix_employees_biz_id'), 'employees', ['biz_id'], unique=False)
    op.create_index(op.f('ix_employees_ten_id'), 'employees', ['ten_id'], unique=False)
    op.drop_column('employees', 'org_id')
    op.add_column('my_tenants', sa.Column('ten_id', sa.Uuid(), nullable=True))
    op.add_column('my_tenants', sa.Column('biz_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_organizations_id'), table_name='my_tenants')
    op.drop_index(op.f('ix_organizations_org_id'), table_name='my_tenants')
    op.create_index(op.f('ix_my_tenants_biz_id'), 'my_tenants', ['biz_id'], unique=False)
    op.create_index(op.f('ix_my_tenants_id'), 'my_tenants', ['id'], unique=False)
    op.create_index(op.f('ix_my_tenants_ten_id'), 'my_tenants', ['ten_id'], unique=False)
    op.drop_column('my_tenants', 'org_id')
    op.add_column('my_users', sa.Column('ten_id', sa.Uuid(), nullable=True))
    op.add_column('my_users', sa.Column('biz_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='my_users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='my_users')
    op.drop_index(op.f('ix_users_id'), table_name='my_users')
    op.drop_index(op.f('ix_users_org_id'), table_name='my_users')
    op.create_index(op.f('ix_my_users_biz_id'), 'my_users', ['biz_id'], unique=False)
    op.create_index(op.f('ix_my_users_email'), 'my_users', ['email'], unique=True)
    op.create_index(op.f('ix_my_users_firebase_uid'), 'my_users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_my_users_id'), 'my_users', ['id'], unique=False)
    op.create_index(op.f('ix_my_users_ten_id'), 'my_users', ['ten_id'], unique=False)
    op.drop_column('my_users', 'org_id')
    op.add_column('payroll_entries', sa.Column('ten_id', sa.Uuid(), nullable=True))
    op.add_column('payroll_entries', sa.Column('biz_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_payroll_entries_org_id'), table_name='payroll_entries')
    op.create_index(op.f('ix_payroll_entries_biz_id'), 'payroll_entries', ['biz_id'], unique=False)
    op.create_index(op.f('ix_payroll_entries_ten_id'), 'payroll_entries', ['ten_id'], unique=False)
    op.drop_column('payroll_entries', 'org_id')
    op.add_column('payroll_periods', sa.Column('ten_id', sa.Uuid(), nullable=True))
    op.add_column('payroll_periods', sa.Column('biz_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_payroll_periods_org_id'), table_name='payroll_periods')
    op.create_index(op.f('ix_payroll_periods_biz_id'), 'payroll_periods', ['biz_id'], unique=False)
    op.create_index(op.f('ix_payroll_periods_ten_id'), 'payroll_periods', ['ten_id'], unique=False)
    op.drop_column('payroll_periods', 'org_id')
    op.add_column('payroll_schedules', sa.Column('ten_id', sa.Uuid(), nullable=True))
    op.add_column('payroll_schedules', sa.Column('biz_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_payroll_schedules_org_id'), table_name='payroll_schedules')
    op.create_index(op.f('ix_payroll_schedules_biz_id'), 'payroll_schedules', ['biz_id'], unique=False)
    op.create_index(op.f('ix_payroll_schedules_ten_id'), 'payroll_schedules', ['ten_id'], unique=False)
    op.drop_column('payroll_schedules', 'org_id')
    op.add_column('t4_records', sa.Column('ten_id', sa.Uuid(), nullable=True))
    op.add_column('t4_records', sa.Column('biz_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_t4_records_org_id'), table_name='t4_records')
    op.create_index(op.f('ix_t4_records_biz_id'), 't4_records', ['biz_id'], unique=False)
    op.create_index(op.f('ix_t4_records_ten_id'), 't4_records', ['ten_id'], unique=False)
    op.drop_column('t4_records', 'org_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t4_records', sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_t4_records_ten_id'), table_name='t4_records')
    op.drop_index(op.f('ix_t4_records_biz_id'), table_name='t4_records')
    op.create_index(op.f('ix_t4_records_org_id'), 't4_records', ['org_id'], unique=False)
    op.drop_column('t4_records', 'biz_id')
    op.drop_column('t4_records', 'ten_id')
    op.add_column('payroll_schedules', sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_payroll_schedules_ten_id'), table_name='payroll_schedules')
    op.drop_index(op.f('ix_payroll_schedules_biz_id'), table_name='payroll_schedules')
    op.create_index(op.f('ix_payroll_schedules_org_id'), 'payroll_schedules', ['org_id'], unique=False)
    op.drop_column('payroll_schedules', 'biz_id')
    op.drop_column('payroll_schedules', 'ten_id')
    op.add_column('payroll_periods', sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_payroll_periods_ten_id'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_biz_id'), table_name='payroll_periods')
    op.create_index(op.f('ix_payroll_periods_org_id'), 'payroll_periods', ['org_id'], unique=False)
    op.drop_column('payroll_periods', 'biz_id')
    op.drop_column('payroll_periods', 'ten_id')
    op.add_column('payroll_entries', sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_payroll_entries_ten_id'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_biz_id'), table_name='payroll_entries')
    op.create_index(op.f('ix_payroll_entries_org_id'), 'payroll_entries', ['org_id'], unique=False)
    op.drop_column('payroll_entries', 'biz_id')
    op.drop_column('payroll_entries', 'ten_id')
    op.add_column('my_users', sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_my_users_ten_id'), table_name='my_users')
    op.drop_index(op.f('ix_my_users_id'), table_name='my_users')
    op.drop_index(op.f('ix_my_users_firebase_uid'), table_name='my_users')
    op.drop_index(op.f('ix_my_users_email'), table_name='my_users')
    op.drop_index(op.f('ix_my_users_biz_id'), table_name='my_users')
    op.create_index(op.f('ix_users_org_id'), 'my_users', ['org_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'my_users', ['id'], unique=False)
    op.create_index(op.f('ix_users_firebase_uid'), 'my_users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_email'), 'my_users', ['email'], unique=True)
    op.drop_column('my_users', 'biz_id')
    op.drop_column('my_users', 'ten_id')
    op.add_column('my_tenants', sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_my_tenants_ten_id'), table_name='my_tenants')
    op.drop_index(op.f('ix_my_tenants_id'), table_name='my_tenants')
    op.drop_index(op.f('ix_my_tenants_biz_id'), table_name='my_tenants')
    op.create_index(op.f('ix_organizations_org_id'), 'my_tenants', ['org_id'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'my_tenants', ['id'], unique=False)
    op.drop_column('my_tenants', 'biz_id')
    op.drop_column('my_tenants', 'ten_id')
    op.add_column('employees', sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_employees_ten_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_biz_id'), table_name='employees')
    op.create_index(op.f('ix_employees_org_id'), 'employees', ['org_id'], unique=False)
    op.drop_column('employees', 'biz_id')
    op.drop_column('employees', 'ten_id')
    op.add_column('cra_submissions', sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_cra_submissions_ten_id'), table_name='cra_submissions')
    op.drop_index(op.f('ix_cra_submissions_biz_id'), table_name='cra_submissions')
    op.create_index(op.f('ix_cra_submissions_org_id'), 'cra_submissions', ['org_id'], unique=False)
    op.drop_column('cra_submissions', 'biz_id')
    op.drop_column('cra_submissions', 'ten_id')
    # ### end Alembic commands ###
