"""my_tenant

Revision ID: 461599cb2031
Revises: 10a54facffec
Create Date: 2026-02-20 16:18:46.056431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461599cb2031'
down_revision: Union[str, Sequence[str], None] = '10a54facffec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_users', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('my_users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('my_users', 'name')
    # ### end Alembic commands ###
