"""employee

Revision ID: 478e1cbf39ac
Revises: fd101077e237
Create Date: 2026-03-01 16:40:09.684943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478e1cbf39ac'
down_revision: Union[str, Sequence[str], None] = 'fd101077e237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('employees', 'sin',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    op.alter_column('employees', 'payroll_schedule_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('employees', 'biz_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_employees_payroll_schedule_id'), table_name='employees')
    op.drop_constraint(op.f('employees_payroll_schedule_id_fkey'), 'employees', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('employees_payroll_schedule_id_fkey'), 'employees', 'payroll_schedules', ['payroll_schedule_id'], ['id'])
    op.create_index(op.f('ix_employees_payroll_schedule_id'), 'employees', ['payroll_schedule_id'], unique=False)
    op.alter_column('employees', 'biz_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('employees', 'payroll_schedule_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('employees', 'sin',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
