"""fk

Revision ID: 4f4189f02efb
Revises: f03ee026c3d9
Create Date: 2026-02-16 00:29:35.906457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4189f02efb'
down_revision: Union[str, Sequence[str], None] = 'f03ee026c3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t4_records', sa.Column('cra_submission_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 't4_records', 'cra_submissions', ['cra_submission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't4_records', type_='foreignkey')
    op.drop_column('t4_records', 'cra_submission_id')
    # ### end Alembic commands ###
