"""add employee

Revision ID: 5bd44146b204
Revises: f8f109aedbf4
Create Date: 2026-03-17 14:10:15.932357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd44146b204'
down_revision: Union[str, Sequence[str], None] = 'f8f109aedbf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_history_period_employee'), 'payroll_history', type_='unique')
    op.create_unique_constraint('uq_history_period', 'payroll_history', ['biz_id', 'schedule_id', 'period_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_history_period', 'payroll_history', type_='unique')
    op.create_unique_constraint(op.f('uq_history_period_employee'), 'payroll_history', ['biz_id', 'schedule_id', 'employee_id', 'period_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
