"""e384

Revision ID: 5ed5bfda48fb
Revises: 7330589af273
Create Date: 2026-03-24 08:01:30.097774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed5bfda48fb'
down_revision: Union[str, Sequence[str], None] = '7330589af273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_emb384_hnsw', 'payroll_history_384', ['emb384'], unique=False, postgresql_using='hnsw', postgresql_ops={'emb384': 'vector_cosine_ops'})
    op.create_index(op.f('ix_payroll_history_384_source_id'), 'payroll_history_384', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_history_384_source_id'), table_name='payroll_history_384')
    op.drop_index('ix_emb384_hnsw', table_name='payroll_history_384', postgresql_using='hnsw', postgresql_ops={'emb384': 'vector_cosine_ops'})
    # ### end Alembic commands ###
