"""fk

Revision ID: 6426bfe48ac2
Revises: 6e7c9242cfdc
Create Date: 2026-03-03 15:40:17.420433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6426bfe48ac2'
down_revision: Union[str, Sequence[str], None] = '6e7c9242cfdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_biz_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_users_active_biz_id'), 'users', ['active_biz_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_active_biz_id'), table_name='users')
    op.drop_column('users', 'active_biz_id')
    # ### end Alembic commands ###
