"""fullname

Revision ID: 653c5d65f38d
Revises: b5b70493368b
Create Date: 2026-03-14 14:46:20.427799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653c5d65f38d'
down_revision: Union[str, Sequence[str], None] = 'b5b70493368b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('full_name', sa.String(), sa.Computed("first_name || ' ' || last_name", persisted=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'full_name')
    # ### end Alembic commands ###
