"""add_invoice

Revision ID: 67354d5da945
Revises: 334df0f712c4
Create Date: 2026-02-23 18:08:58.336754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67354d5da945'
down_revision: Union[str, Sequence[str], None] = '334df0f712c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biz_entities', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_biz_entities_owner_id'), 'biz_entities', ['owner_id'], unique=False)
    op.add_column('cra_submissions', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_cra_submissions_owner_id'), 'cra_submissions', ['owner_id'], unique=False)
    op.add_column('employees', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_employees_owner_id'), 'employees', ['owner_id'], unique=False)
    op.add_column('invoices', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_invoices_owner_id'), 'invoices', ['owner_id'], unique=False)
    op.add_column('my_tenants', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_my_tenants_owner_id'), 'my_tenants', ['owner_id'], unique=False)
    op.add_column('my_users', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_my_users_owner_id'), 'my_users', ['owner_id'], unique=False)
    op.add_column('payroll_entries', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_payroll_entries_owner_id'), 'payroll_entries', ['owner_id'], unique=False)
    op.add_column('payroll_periods', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_payroll_periods_owner_id'), 'payroll_periods', ['owner_id'], unique=False)
    op.add_column('payroll_schedules', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_payroll_schedules_owner_id'), 'payroll_schedules', ['owner_id'], unique=False)
    op.add_column('t4_records', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_t4_records_owner_id'), 't4_records', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t4_records_owner_id'), table_name='t4_records')
    op.drop_column('t4_records', 'owner_id')
    op.drop_index(op.f('ix_payroll_schedules_owner_id'), table_name='payroll_schedules')
    op.drop_column('payroll_schedules', 'owner_id')
    op.drop_index(op.f('ix_payroll_periods_owner_id'), table_name='payroll_periods')
    op.drop_column('payroll_periods', 'owner_id')
    op.drop_index(op.f('ix_payroll_entries_owner_id'), table_name='payroll_entries')
    op.drop_column('payroll_entries', 'owner_id')
    op.drop_index(op.f('ix_my_users_owner_id'), table_name='my_users')
    op.drop_column('my_users', 'owner_id')
    op.drop_index(op.f('ix_my_tenants_owner_id'), table_name='my_tenants')
    op.drop_column('my_tenants', 'owner_id')
    op.drop_index(op.f('ix_invoices_owner_id'), table_name='invoices')
    op.drop_column('invoices', 'owner_id')
    op.drop_index(op.f('ix_employees_owner_id'), table_name='employees')
    op.drop_column('employees', 'owner_id')
    op.drop_index(op.f('ix_cra_submissions_owner_id'), table_name='cra_submissions')
    op.drop_column('cra_submissions', 'owner_id')
    op.drop_index(op.f('ix_biz_entities_owner_id'), table_name='biz_entities')
    op.drop_column('biz_entities', 'owner_id')
    # ### end Alembic commands ###
