"""stripe

Revision ID: 69587242bb7a
Revises: 2ce236c782ba
Create Date: 2026-03-15 19:21:24.621660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69587242bb7a'
down_revision: Union[str, Sequence[str], None] = '2ce236c782ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biz_entities', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('biz_entities', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    op.add_column('biz_entities', sa.Column('stripe_price_id', sa.String(), nullable=True))
    op.add_column('biz_entities', sa.Column('stripe_status', sa.String(), nullable=True))
    op.add_column('biz_entities', sa.Column('stripe_current_period_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('biz_entities', sa.Column('stripe_cancel_at_period_end', sa.Boolean(), nullable=True))
    op.add_column('biz_entities', sa.Column('stripe_cancel_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('biz_entities', sa.Column('stripe_plan_key', sa.String(), nullable=True))
    op.add_column('biz_entities', sa.Column('stripe_interval', sa.String(), nullable=True))
    op.add_column('biz_entities', sa.Column('stripe_latest_event_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_biz_entities_stripe_customer_id'), 'biz_entities', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_biz_entities_stripe_subscription_id'), 'biz_entities', ['stripe_subscription_id'], unique=False)
    op.alter_column('payroll_history', 'excluded',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payroll_history', 'excluded',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_biz_entities_stripe_subscription_id'), table_name='biz_entities')
    op.drop_index(op.f('ix_biz_entities_stripe_customer_id'), table_name='biz_entities')
    op.drop_column('biz_entities', 'stripe_latest_event_id')
    op.drop_column('biz_entities', 'stripe_interval')
    op.drop_column('biz_entities', 'stripe_plan_key')
    op.drop_column('biz_entities', 'stripe_cancel_at')
    op.drop_column('biz_entities', 'stripe_cancel_at_period_end')
    op.drop_column('biz_entities', 'stripe_current_period_end')
    op.drop_column('biz_entities', 'stripe_status')
    op.drop_column('biz_entities', 'stripe_price_id')
    op.drop_column('biz_entities', 'stripe_subscription_id')
    op.drop_column('biz_entities', 'stripe_customer_id')
    # ### end Alembic commands ###
