"""fk

Revision ID: 6e7c9242cfdc
Revises: 7406c120f39a
Create Date: 2026-03-03 15:27:25.855893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e7c9242cfdc'
down_revision: Union[str, Sequence[str], None] = '7406c120f39a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('biz_id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['biz_id'], ['biz_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'biz_id', name='uq_user_clients_user_biz')
    )
    op.create_index(op.f('ix_user_clients_biz_id'), 'user_clients', ['biz_id'], unique=False)
    op.create_index(op.f('ix_user_clients_id'), 'user_clients', ['id'], unique=False)
    op.create_index(op.f('ix_user_clients_ten_id'), 'user_clients', ['ten_id'], unique=False)
    op.create_index(op.f('ix_user_clients_user_id'), 'user_clients', ['user_id'], unique=False)
    op.drop_index(op.f('ix_z_user_ten_biz_id'), table_name='z_user_ten')
    op.drop_index(op.f('ix_z_user_ten_firebase_uid'), table_name='z_user_ten')
    op.drop_index(op.f('ix_z_user_ten_id'), table_name='z_user_ten')
    op.drop_index(op.f('ix_z_user_ten_owner_id'), table_name='z_user_ten')
    op.drop_index(op.f('ix_z_user_ten_ten_id'), table_name='z_user_ten')
    op.drop_table('z_user_ten')
    op.add_column('biz_entities', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_biz_entities_created_by'), 'biz_entities', ['created_by'], unique=False)
    op.add_column('cra_submissions', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_cra_submissions_created_by'), 'cra_submissions', ['created_by'], unique=False)
    op.add_column('employees', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_employees_created_by'), 'employees', ['created_by'], unique=False)
    op.add_column('invoices', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_invoices_created_by'), 'invoices', ['created_by'], unique=False)
    op.add_column('payroll_entries', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_payroll_entries_created_by'), 'payroll_entries', ['created_by'], unique=False)
    op.add_column('payroll_periods', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_payroll_periods_created_by'), 'payroll_periods', ['created_by'], unique=False)
    op.add_column('payroll_schedules', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_payroll_schedules_created_by'), 'payroll_schedules', ['created_by'], unique=False)
    op.add_column('t4_records', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_t4_records_created_by'), 't4_records', ['created_by'], unique=False)
    op.add_column('users', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_users_created_by'), 'users', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_by'), table_name='users')
    op.drop_column('users', 'created_by')
    op.drop_index(op.f('ix_t4_records_created_by'), table_name='t4_records')
    op.drop_column('t4_records', 'created_by')
    op.drop_index(op.f('ix_payroll_schedules_created_by'), table_name='payroll_schedules')
    op.drop_column('payroll_schedules', 'created_by')
    op.drop_index(op.f('ix_payroll_periods_created_by'), table_name='payroll_periods')
    op.drop_column('payroll_periods', 'created_by')
    op.drop_index(op.f('ix_payroll_entries_created_by'), table_name='payroll_entries')
    op.drop_column('payroll_entries', 'created_by')
    op.drop_index(op.f('ix_invoices_created_by'), table_name='invoices')
    op.drop_column('invoices', 'created_by')
    op.drop_index(op.f('ix_employees_created_by'), table_name='employees')
    op.drop_column('employees', 'created_by')
    op.drop_index(op.f('ix_cra_submissions_created_by'), table_name='cra_submissions')
    op.drop_column('cra_submissions', 'created_by')
    op.drop_index(op.f('ix_biz_entities_created_by'), table_name='biz_entities')
    op.drop_column('biz_entities', 'created_by')
    op.create_table('z_user_ten',
    sa.Column('firebase_uid', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ten_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('biz_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('b_int', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('b_str', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('b_decimal', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('b_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('b_bool', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_flag', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('z_user_ten_pkey'))
    )
    op.create_index(op.f('ix_z_user_ten_ten_id'), 'z_user_ten', ['ten_id'], unique=False)
    op.create_index(op.f('ix_z_user_ten_owner_id'), 'z_user_ten', ['owner_id'], unique=False)
    op.create_index(op.f('ix_z_user_ten_id'), 'z_user_ten', ['id'], unique=False)
    op.create_index(op.f('ix_z_user_ten_firebase_uid'), 'z_user_ten', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_z_user_ten_biz_id'), 'z_user_ten', ['biz_id'], unique=False)
    op.drop_index(op.f('ix_user_clients_user_id'), table_name='user_clients')
    op.drop_index(op.f('ix_user_clients_ten_id'), table_name='user_clients')
    op.drop_index(op.f('ix_user_clients_id'), table_name='user_clients')
    op.drop_index(op.f('ix_user_clients_biz_id'), table_name='user_clients')
    op.drop_table('user_clients')
    # ### end Alembic commands ###
