"""position

Revision ID: 7104aedbe160
Revises: b76a3567efe3
Create Date: 2026-03-08 23:06:27.806021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7104aedbe160'
down_revision: Union[str, Sequence[str], None] = 'b76a3567efe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_periods', sa.Column('period_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_periods', 'period_number')
    # ### end Alembic commands ###
