"""weekday

Revision ID: 730c8eb0796f
Revises: c94c5d210f66
Create Date: 2026-03-11 22:03:17.144564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730c8eb0796f'
down_revision: Union[str, Sequence[str], None] = 'c94c5d210f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_schedules', sa.Column('weekday', sa.String(), nullable=True))
    op.add_column('payroll_schedules', sa.Column('monthday', sa.Integer(), nullable=True))
    op.add_column('payroll_schedules', sa.Column('semimonthday1', sa.Integer(), nullable=True))
    op.add_column('payroll_schedules', sa.Column('semimonthday2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_schedules', 'semimonthday2')
    op.drop_column('payroll_schedules', 'semimonthday1')
    op.drop_column('payroll_schedules', 'monthday')
    op.drop_column('payroll_schedules', 'weekday')
    # ### end Alembic commands ###
