"""e384

Revision ID: 7330589af273
Revises: 19f015eaf82f
Create Date: 2026-03-23 22:51:20.158726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '7330589af273'
down_revision: Union[str, Sequence[str], None] = '19f015eaf82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_history_384', sa.Column('emb384', Vector(dim=384), nullable=False))
    op.drop_column('payroll_history_384', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_history_384', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), autoincrement=False, nullable=False))
    op.drop_column('payroll_history_384', 'emb384')
    # ### end Alembic commands ###
