"""employee

Revision ID: 7406c120f39a
Revises: 79c94d76d470
Create Date: 2026-03-02 07:00:01.885112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7406c120f39a'
down_revision: Union[str, Sequence[str], None] = '79c94d76d470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'payroll_schedule_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('payroll_schedule_id', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
