"""employee

Revision ID: 79c94d76d470
Revises: dc7c1e3368c0
Create Date: 2026-03-02 06:39:31.490194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c94d76d470'
down_revision: Union[str, Sequence[str], None] = 'dc7c1e3368c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_entries', sa.Column('cpp_exempt_snapshot', sa.Boolean(), nullable=False))
    op.add_column('payroll_entries', sa.Column('ei_exempt_snapshot', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_entries', 'ei_exempt_snapshot')
    op.drop_column('payroll_entries', 'cpp_exempt_snapshot')
    # ### end Alembic commands ###
