"""payon

Revision ID: 7b12e6d64aeb
Revises: 9b2f0c2a3c10
Create Date: 2026-03-12 00:08:24.760432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b12e6d64aeb'
down_revision: Union[str, Sequence[str], None] = '9b2f0c2a3c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_schedules', sa.Column('payon', sa.String(), nullable=True))
    op.drop_column('payroll_schedules', 'semimonthday1')
    op.drop_column('payroll_schedules', 'weekday')
    op.drop_column('payroll_schedules', 'semimonthday2')
    op.drop_column('payroll_schedules', 'monthday')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_schedules', sa.Column('monthday', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('payroll_schedules', sa.Column('semimonthday2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('payroll_schedules', sa.Column('weekday', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payroll_schedules', sa.Column('semimonthday1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('payroll_schedules', 'payon')
    # ### end Alembic commands ###
