"""update base

Revision ID: 8167dc0776bc
Revises: 7ac0f8da75fc
Create Date: 2026-02-13 17:57:23.110667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8167dc0776bc'
down_revision: Union[str, Sequence[str], None] = '7ac0f8da75fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cra_submissions',
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('business_number', sa.String(length=9), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'REJECTED', 'ACCEPTED', name='submissionstatus'), nullable=False),
    sa.Column('submitted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('xml_content', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cra_submissions_id'), 'cra_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_cra_submissions_tenant_id'), 'cra_submissions', ['tenant_id'], unique=False)
    op.create_table('employees',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('sin', sa.String(length=9), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sin')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_tenant_id'), 'employees', ['tenant_id'], unique=False)
    op.create_table('t4_records',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('employment_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cpp_contributions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ei_premiums', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('income_tax_deducted', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t4_records_id'), 't4_records', ['id'], unique=False)
    op.create_index(op.f('ix_t4_records_tenant_id'), 't4_records', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t4_records_tenant_id'), table_name='t4_records')
    op.drop_index(op.f('ix_t4_records_id'), table_name='t4_records')
    op.drop_table('t4_records')
    op.drop_index(op.f('ix_employees_tenant_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_cra_submissions_tenant_id'), table_name='cra_submissions')
    op.drop_index(op.f('ix_cra_submissions_id'), table_name='cra_submissions')
    op.drop_table('cra_submissions')
    # ### end Alembic commands ###
