"""zme

Revision ID: 82e970ebeca5
Revises: 1413b0e217b1
Create Date: 2026-03-04 07:34:58.697789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e970ebeca5'
down_revision: Union[str, Sequence[str], None] = '1413b0e217b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_active_biz_id'), table_name='users')
    op.drop_column('users', 'active_biz_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_biz_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_active_biz_id'), 'users', ['active_biz_id'], unique=False)
    # ### end Alembic commands ###
