"""hrs 

Revision ID: 830578af0d09
Revises: 8f9c8a0f6524
Create Date: 2026-03-12 08:51:03.049375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830578af0d09'
down_revision: Union[str, Sequence[str], None] = '8f9c8a0f6524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_schedules', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_schedules', 'note')
    # ### end Alembic commands ###
