"""role

Revision ID: 848215839170
Revises: 678c3c66dc0d
Create Date: 2026-02-14 22:33:45.886123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848215839170'
down_revision: Union[str, Sequence[str], None] = '678c3c66dc0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cra_submissions', sa.Column('org_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_cra_submissions_tenant_id'), table_name='cra_submissions')
    op.create_index(op.f('ix_cra_submissions_org_id'), 'cra_submissions', ['org_id'], unique=False)
    op.drop_column('cra_submissions', 'tenant_id')
    op.add_column('employees', sa.Column('org_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_employees_tenant_id'), table_name='employees')
    op.create_index(op.f('ix_employees_org_id'), 'employees', ['org_id'], unique=False)
    op.drop_column('employees', 'tenant_id')
    op.add_column('t4_records', sa.Column('org_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_t4_records_tenant_id'), table_name='t4_records')
    op.create_index(op.f('ix_t4_records_org_id'), 't4_records', ['org_id'], unique=False)
    op.drop_column('t4_records', 'tenant_id')
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.add_column('users', sa.Column('type', sa.String(), nullable=False))
    op.add_column('users', sa.Column('group', sa.String(), nullable=False))
    op.add_column('users', sa.Column('org_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.drop_column('users', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.drop_column('users', 'org_id')
    op.drop_column('users', 'group')
    op.drop_column('users', 'type')
    op.drop_column('users', 'role')
    op.add_column('t4_records', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_t4_records_org_id'), table_name='t4_records')
    op.create_index(op.f('ix_t4_records_tenant_id'), 't4_records', ['tenant_id'], unique=False)
    op.drop_column('t4_records', 'org_id')
    op.add_column('employees', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_employees_org_id'), table_name='employees')
    op.create_index(op.f('ix_employees_tenant_id'), 'employees', ['tenant_id'], unique=False)
    op.drop_column('employees', 'org_id')
    op.add_column('cra_submissions', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_cra_submissions_org_id'), table_name='cra_submissions')
    op.create_index(op.f('ix_cra_submissions_tenant_id'), 'cra_submissions', ['tenant_id'], unique=False)
    op.drop_column('cra_submissions', 'org_id')
    # ### end Alembic commands ###
