"""my_tenant

Revision ID: 85cde653a7c0
Revises: 1e1e3cd3689d
Create Date: 2026-02-19 09:26:09.079226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85cde653a7c0'
down_revision: Union[str, Sequence[str], None] = '1e1e3cd3689d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('my_users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('my_users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('my_users', sa.Column('position', sa.String(), nullable=True))
    op.add_column('my_users', sa.Column('facebook', sa.String(), nullable=True))
    op.add_column('my_users', sa.Column('twitter', sa.String(), nullable=True))
    op.add_column('my_users', sa.Column('github', sa.String(), nullable=True))
    op.add_column('my_users', sa.Column('reddit', sa.String(), nullable=True))
    op.add_column('my_users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('my_users', sa.Column('state', sa.String(), nullable=True))
    op.add_column('my_users', sa.Column('pin', sa.String(), nullable=True))
    op.add_column('my_users', sa.Column('zip', sa.String(), nullable=True))
    op.add_column('my_users', sa.Column('tax_no', sa.String(), nullable=True))
    op.alter_column('my_users', 'firebase_uid',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('my_users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('my_users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('my_users', 'group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('my_users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('my_users', 'group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('my_users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('my_users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('my_users', 'firebase_uid',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('my_users', 'tax_no')
    op.drop_column('my_users', 'zip')
    op.drop_column('my_users', 'pin')
    op.drop_column('my_users', 'state')
    op.drop_column('my_users', 'location')
    op.drop_column('my_users', 'reddit')
    op.drop_column('my_users', 'github')
    op.drop_column('my_users', 'twitter')
    op.drop_column('my_users', 'facebook')
    op.drop_column('my_users', 'position')
    op.drop_column('my_users', 'phone')
    op.drop_column('my_users', 'last_name')
    op.drop_column('my_users', 'first_name')
    # ### end Alembic commands ###
