"""payroll

Revision ID: 87fa8e031ff1
Revises: 1883ba7cb3e0
Create Date: 2026-02-18 00:43:22.479166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87fa8e031ff1'
down_revision: Union[str, Sequence[str], None] = '1883ba7cb3e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't4_records', type_='foreignkey')
    op.drop_index(op.f('ix_payroll_entries_payroll_period_id'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_org_id'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_id'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_employee_id'), table_name='payroll_entries')
    op.drop_table('payroll_entries')
    op.drop_index(op.f('ix_payroll_periods_payroll_schedule_id'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_org_id'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_id'), table_name='payroll_periods')
    op.drop_table('payroll_periods')
    op.drop_index(op.f('ix_employees_payroll_schedule_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_org_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_payroll_schedules_org_id'), table_name='payroll_schedules')
    op.drop_index(op.f('ix_payroll_schedules_id'), table_name='payroll_schedules')
    op.drop_table('payroll_schedules')
    # ### end Alembic commands ###
