"""hrs perday

Revision ID: 8b680ebe2153
Revises: 307f850278c9
Create Date: 2026-03-09 18:23:56.351998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b680ebe2153'
down_revision: Union[str, Sequence[str], None] = '307f850278c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_entries', sa.Column('full_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_entries', 'full_name')
    # ### end Alembic commands ###
