"""guardrail

Revision ID: 8cc196b2c58f
Revises: b28c2c06c09e
Create Date: 2026-04-03 13:14:13.330770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cc196b2c58f'
down_revision: Union[str, Sequence[str], None] = 'b28c2c06c09e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_guardrail_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('route', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('judge_model', sa.Text(), nullable=True),
    sa.Column('is_hallucination', sa.Boolean(), nullable=True),
    sa.Column('is_refusal', sa.Boolean(), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), nullable=True),
    sa.Column('latency_ms', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_guardrail_event_biz_id'), 'ai_guardrail_event', ['biz_id'], unique=False)
    op.create_index(op.f('ix_ai_guardrail_event_model'), 'ai_guardrail_event', ['model'], unique=False)
    op.create_index(op.f('ix_ai_guardrail_event_route'), 'ai_guardrail_event', ['route'], unique=False)
    op.create_index(op.f('ix_ai_guardrail_event_ten_id'), 'ai_guardrail_event', ['ten_id'], unique=False)
    op.create_index(op.f('ix_ai_guardrail_event_user_id'), 'ai_guardrail_event', ['user_id'], unique=False)
    op.drop_index(op.f('ix_emb384_chunk_tsv_gin'), table_name='payroll_history_384', postgresql_using='gin')
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', postgresql_using='gin')
    op.create_index(op.f('ix_emb384_chunk_tsv_gin'), 'payroll_history_384', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_ai_guardrail_event_user_id'), table_name='ai_guardrail_event')
    op.drop_index(op.f('ix_ai_guardrail_event_ten_id'), table_name='ai_guardrail_event')
    op.drop_index(op.f('ix_ai_guardrail_event_route'), table_name='ai_guardrail_event')
    op.drop_index(op.f('ix_ai_guardrail_event_model'), table_name='ai_guardrail_event')
    op.drop_index(op.f('ix_ai_guardrail_event_biz_id'), table_name='ai_guardrail_event')
    op.drop_table('ai_guardrail_event')
    # ### end Alembic commands ###
