"""emp_biz

Revision ID: 8e0d60443dcb
Revises: c5044b1e6f2f
Create Date: 2026-03-01 06:20:27.001204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e0d60443dcb'
down_revision: Union[str, Sequence[str], None] = 'c5044b1e6f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'biz_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'employees', 'biz_entities', ['biz_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.alter_column('employees', 'biz_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
