"""semi1

Revision ID: 8f9c8a0f6524
Revises: 15f5dc556088
Create Date: 2026-03-12 06:53:22.571350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9c8a0f6524'
down_revision: Union[str, Sequence[str], None] = '15f5dc556088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_schedules', sa.Column('period', sa.String(), nullable=True))
    op.alter_column('payroll_schedules', 'frequency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('payroll_schedules', 'effective_from',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('payroll_schedules', 'anchor_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_schedules', sa.Column('anchor_date', sa.DATE(), autoincrement=False, nullable=False))
    op.alter_column('payroll_schedules', 'effective_from',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('payroll_schedules', 'frequency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('payroll_schedules', 'period')
    # ### end Alembic commands ###
