"""payroll

Revision ID: a632e92064a9
Revises: 42c17c9b7413
Create Date: 2026-02-16 23:36:19.045867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a632e92064a9'
down_revision: Union[str, Sequence[str], None] = '42c17c9b7413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_entries', sa.Column('total_deduction', sa.Numeric(precision=18, scale=2), nullable=False))
    op.alter_column('payroll_entries', 'gross',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('payroll_entries', 'net',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_payroll_entries_employee_id'), 'payroll_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_entries_payroll_period_id'), 'payroll_entries', ['payroll_period_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_entries_payroll_period_id'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_employee_id'), table_name='payroll_entries')
    op.alter_column('payroll_entries', 'net',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('payroll_entries', 'gross',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('payroll_entries', 'total_deduction')
    # ### end Alembic commands ###
