"""sin

Revision ID: aa6945b15d46
Revises: 69587242bb7a
Create Date: 2026-03-16 20:12:29.335366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6945b15d46'
down_revision: Union[str, Sequence[str], None] = '69587242bb7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employees_sin_key'), 'employees', type_='unique')
    op.alter_column('payroll_history', 'excluded',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payroll_history', 'excluded',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint(op.f('employees_sin_key'), 'employees', ['sin'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
