"""goldds

Revision ID: b28c2c06c09e
Revises: c90cfde6e17f
Create Date: 2026-04-02 17:36:38.546175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b28c2c06c09e'
down_revision: Union[str, Sequence[str], None] = 'c90cfde6e17f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_eval_dataset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=False),
    sa.Column('relevant_source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_eval_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('embedding_version', sa.Text(), nullable=True),
    sa.Column('model_version', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_eval_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('retrieved_source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('recall_at_k', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('precision_at_k', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('is_faithful', sa.Boolean(), nullable=True),
    sa.Column('eval_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['rag_eval_dataset.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['rag_eval_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_eval_result_dataset_id'), 'rag_eval_result', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_rag_eval_result_run_id'), 'rag_eval_result', ['run_id'], unique=False)
    op.drop_index(op.f('ix_emb384_chunk_tsv_gin'), table_name='payroll_history_384', postgresql_using='gin')
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', postgresql_using='gin')
    op.create_index(op.f('ix_emb384_chunk_tsv_gin'), 'payroll_history_384', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_rag_eval_result_run_id'), table_name='rag_eval_result')
    op.drop_index(op.f('ix_rag_eval_result_dataset_id'), table_name='rag_eval_result')
    op.drop_table('rag_eval_result')
    op.drop_table('rag_eval_run')
    op.drop_table('rag_eval_dataset')
    # ### end Alembic commands ###
