"""period

Revision ID: b550f72b5b23
Revises: 5bd44146b204
Create Date: 2026-03-17 17:44:15.573696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b550f72b5b23'
down_revision: Union[str, Sequence[str], None] = '5bd44146b204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_periods',
    sa.Column('payroll_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('pay_date', sa.Date(), nullable=True),
    sa.Column('period_key', sa.String(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['payroll_schedule_id'], ['payroll_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('biz_id', 'period_key', name='uq_payroll_period_key')
    )
    op.create_index(op.f('ix_payroll_periods_biz_id'), 'payroll_periods', ['biz_id'], unique=False)
    op.create_index(op.f('ix_payroll_periods_created_by'), 'payroll_periods', ['created_by'], unique=False)
    op.create_index(op.f('ix_payroll_periods_end_date'), 'payroll_periods', ['end_date'], unique=False)
    op.create_index(op.f('ix_payroll_periods_id'), 'payroll_periods', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_periods_owner_id'), 'payroll_periods', ['owner_id'], unique=False)
    op.create_index(op.f('ix_payroll_periods_pay_date'), 'payroll_periods', ['pay_date'], unique=False)
    op.create_index(op.f('ix_payroll_periods_payroll_schedule_id'), 'payroll_periods', ['payroll_schedule_id'], unique=False)
    op.create_index(op.f('ix_payroll_periods_period_key'), 'payroll_periods', ['period_key'], unique=False)
    op.create_index(op.f('ix_payroll_periods_start_date'), 'payroll_periods', ['start_date'], unique=False)
    op.create_index(op.f('ix_payroll_periods_ten_id'), 'payroll_periods', ['ten_id'], unique=False)
    op.add_column('payroll_entries', sa.Column('payroll_period_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_payroll_entries_payroll_period_id'), 'payroll_entries', ['payroll_period_id'], unique=False)
    op.create_foreign_key(None, 'payroll_entries', 'payroll_periods', ['payroll_period_id'], ['id'])
    op.add_column('payroll_history', sa.Column('payroll_period_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('uq_history_period'), 'payroll_history', type_='unique')
    op.create_index(op.f('ix_payroll_history_payroll_period_id'), 'payroll_history', ['payroll_period_id'], unique=False)
    op.create_foreign_key(None, 'payroll_history', 'payroll_periods', ['payroll_period_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payroll_history', type_='foreignkey')
    op.drop_index(op.f('ix_payroll_history_payroll_period_id'), table_name='payroll_history')
    op.create_unique_constraint(op.f('uq_history_period'), 'payroll_history', ['biz_id', 'schedule_id', 'period_key'], postgresql_nulls_not_distinct=False)
    op.drop_column('payroll_history', 'payroll_period_id')
    op.drop_constraint(None, 'payroll_entries', type_='foreignkey')
    op.drop_index(op.f('ix_payroll_entries_payroll_period_id'), table_name='payroll_entries')
    op.drop_column('payroll_entries', 'payroll_period_id')
    op.drop_index(op.f('ix_payroll_periods_ten_id'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_start_date'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_period_key'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_payroll_schedule_id'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_pay_date'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_owner_id'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_id'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_end_date'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_created_by'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_biz_id'), table_name='payroll_periods')
    op.drop_table('payroll_periods')
    # ### end Alembic commands ###
