"""paydate 

Revision ID: b5b70493368b
Revises: daa8a434f093
Create Date: 2026-03-14 14:31:00.855037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b70493368b'
down_revision: Union[str, Sequence[str], None] = 'daa8a434f093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_entries', sa.Column('pay_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_payroll_entries_pay_date'), 'payroll_entries', ['pay_date'], unique=False)
    op.add_column('payroll_history', sa.Column('pay_date', sa.Date(), nullable=True))
    op.drop_column('payroll_history', 'pay_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_history', sa.Column('pay_day', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('payroll_history', 'pay_date')
    op.drop_index(op.f('ix_payroll_entries_pay_date'), table_name='payroll_entries')
    op.drop_column('payroll_entries', 'pay_date')
    # ### end Alembic commands ###
