"""position

Revision ID: b76a3567efe3
Revises: 34b45438832c
Create Date: 2026-03-08 19:42:10.831836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b76a3567efe3'
down_revision: Union[str, Sequence[str], None] = '34b45438832c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('position', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'position')
    op.drop_column('employees', 'phone')
    # ### end Alembic commands ###
