"""fk

Revision ID: c3599f7d7766
Revises: 4f4189f02efb
Create Date: 2026-02-16 00:33:45.081652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3599f7d7766'
down_revision: Union[str, Sequence[str], None] = '4f4189f02efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cra_submissions', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SUBMITTED', 'REJECTED', 'ACCEPTED', name='submissionstatus'),
               type_=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cra_submissions', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('DRAFT', 'SUBMITTED', 'REJECTED', 'ACCEPTED', name='submissionstatus'),
               nullable=False)
    # ### end Alembic commands ###
