"""reddit

Revision ID: c5044b1e6f2f
Revises: dd0e7126f3eb
Create Date: 2026-02-26 12:18:39.110037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5044b1e6f2f'
down_revision: Union[str, Sequence[str], None] = 'dd0e7126f3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reddit', sa.String(), nullable=True))
    op.drop_column('users', 'dribbble')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dribbble', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'reddit')
    # ### end Alembic commands ###
