"""cahce

Revision ID: c90cfde6e17f
Revises: 377fcaa8f830
Create Date: 2026-03-25 18:11:09.294503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c90cfde6e17f'
down_revision: Union[str, Sequence[str], None] = '377fcaa8f830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=False),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ten_id', 'cache_key', name='uq_agent_cache_ten_key')
    )
    op.create_index(op.f('ix_agent_cache_biz_id'), 'agent_cache', ['biz_id'], unique=False)
    op.create_index(op.f('ix_agent_cache_cache_key'), 'agent_cache', ['cache_key'], unique=False)
    op.create_index(op.f('ix_agent_cache_expires_at'), 'agent_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_agent_cache_id'), 'agent_cache', ['id'], unique=False)
    op.create_index(op.f('ix_agent_cache_ten_id'), 'agent_cache', ['ten_id'], unique=False)
    op.drop_index(op.f('ix_emb384_chunk_tsv_gin'), table_name='payroll_history_384', postgresql_using='gin')
    op.create_index('ix_emb384_chunk_tsv_gin', 'payroll_history_384', [sa.literal_column("to_tsvector(CAST('english' AS REGCONFIG), chunk)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_emb384_chunk_tsv_gin', table_name='payroll_history_384', postgresql_using='gin')
    op.create_index(op.f('ix_emb384_chunk_tsv_gin'), 'payroll_history_384', [sa.literal_column("to_tsvector('english'::regconfig, chunk)")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_agent_cache_ten_id'), table_name='agent_cache')
    op.drop_index(op.f('ix_agent_cache_id'), table_name='agent_cache')
    op.drop_index(op.f('ix_agent_cache_expires_at'), table_name='agent_cache')
    op.drop_index(op.f('ix_agent_cache_cache_key'), table_name='agent_cache')
    op.drop_index(op.f('ix_agent_cache_biz_id'), table_name='agent_cache')
    op.drop_table('agent_cache')
    # ### end Alembic commands ###
