"""hrs perday

Revision ID: c94c5d210f66
Revises: 8b680ebe2153
Create Date: 2026-03-09 18:32:37.491046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94c5d210f66'
down_revision: Union[str, Sequence[str], None] = '8b680ebe2153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_entries', sa.Column('adjustment', sa.Numeric(precision=18, scale=2), nullable=True))
    op.alter_column('payroll_entries', 'employment_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payroll_entries', 'employment_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('payroll_entries', 'adjustment')
    # ### end Alembic commands ###
