"""history

Revision ID: d90d2abd71ad
Revises: 3ce6395aa1d4
Create Date: 2026-03-13 22:03:58.381682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd90d2abd71ad'
down_revision: Union[str, Sequence[str], None] = '3ce6395aa1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_history',
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('pay_day', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('annual_salary_snapshot', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('hourly_rate_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('federal_claim_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ontario_claim_snapshot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('regular_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('overtime_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bonus', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vacation', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cpp', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('ei', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_deduction', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('adjustment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cpp_exempt_snapshot', sa.Boolean(), nullable=False),
    sa.Column('ei_exempt_snapshot', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ten_id', sa.Uuid(), nullable=True),
    sa.Column('biz_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['payroll_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('biz_id', 'schedule_id', 'employee_id', 'period_start', 'period_end', name='uq_history_period_employee')
    )
    op.create_index(op.f('ix_payroll_history_biz_id'), 'payroll_history', ['biz_id'], unique=False)
    op.create_index(op.f('ix_payroll_history_created_by'), 'payroll_history', ['created_by'], unique=False)
    op.create_index(op.f('ix_payroll_history_employee_id'), 'payroll_history', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_history_id'), 'payroll_history', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_history_owner_id'), 'payroll_history', ['owner_id'], unique=False)
    op.create_index(op.f('ix_payroll_history_period_end'), 'payroll_history', ['period_end'], unique=False)
    op.create_index(op.f('ix_payroll_history_period_start'), 'payroll_history', ['period_start'], unique=False)
    op.create_index(op.f('ix_payroll_history_schedule_id'), 'payroll_history', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_payroll_history_ten_id'), 'payroll_history', ['ten_id'], unique=False)
    op.alter_column('payroll_entries', 'schedule_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('payroll_entries', sa.Column('period_start', sa.Date(), nullable=True))
    op.add_column('payroll_entries', sa.Column('period_end', sa.Date(), nullable=True))
    op.create_index(op.f('ix_payroll_entries_period_start'), 'payroll_entries', ['period_start'], unique=False)
    op.create_index(op.f('ix_payroll_entries_period_end'), 'payroll_entries', ['period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payroll_entries', 'schedule_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_payroll_entries_period_end'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_period_start'), table_name='payroll_entries')
    op.drop_column('payroll_entries', 'period_end')
    op.drop_column('payroll_entries', 'period_start')
    op.drop_index(op.f('ix_payroll_history_ten_id'), table_name='payroll_history')
    op.drop_index(op.f('ix_payroll_history_schedule_id'), table_name='payroll_history')
    op.drop_index(op.f('ix_payroll_history_period_start'), table_name='payroll_history')
    op.drop_index(op.f('ix_payroll_history_period_end'), table_name='payroll_history')
    op.drop_index(op.f('ix_payroll_history_owner_id'), table_name='payroll_history')
    op.drop_index(op.f('ix_payroll_history_id'), table_name='payroll_history')
    op.drop_index(op.f('ix_payroll_history_employee_id'), table_name='payroll_history')
    op.drop_index(op.f('ix_payroll_history_created_by'), table_name='payroll_history')
    op.drop_index(op.f('ix_payroll_history_biz_id'), table_name='payroll_history')
    op.drop_table('payroll_history')
    # ### end Alembic commands ###
