"""fixedperiod

Revision ID: daa8a434f093
Revises: fa77642195b4
Create Date: 2026-03-14 10:58:01.146876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa8a434f093'
down_revision: Union[str, Sequence[str], None] = 'fa77642195b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_entries', sa.Column('period_key', sa.String(), nullable=True))
    op.drop_constraint(op.f('uq_schedule_employee'), 'payroll_entries', type_='unique')
    op.create_index(op.f('ix_payroll_entries_period_key'), 'payroll_entries', ['period_key'], unique=False)
    op.create_unique_constraint('uq_schedule_employee_period', 'payroll_entries', ['schedule_id', 'employee_id', 'period_key'])
    op.add_column('payroll_history', sa.Column('period_key', sa.String(), nullable=False))
    op.alter_column('payroll_history', 'period_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('payroll_history', 'period_end',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint(op.f('uq_history_period_employee'), 'payroll_history', type_='unique')
    op.create_unique_constraint('uq_history_period_employee', 'payroll_history', ['biz_id', 'schedule_id', 'employee_id', 'period_key'])
    op.create_index(op.f('ix_payroll_history_period_key'), 'payroll_history', ['period_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_history_period_key'), table_name='payroll_history')
    op.drop_constraint('uq_history_period_employee', 'payroll_history', type_='unique')
    op.create_unique_constraint(op.f('uq_history_period_employee'), 'payroll_history', ['biz_id', 'schedule_id', 'employee_id', 'period_start', 'period_end'], postgresql_nulls_not_distinct=False)
    op.alter_column('payroll_history', 'period_end',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('payroll_history', 'period_start',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_column('payroll_history', 'period_key')
    op.drop_constraint('uq_schedule_employee_period', 'payroll_entries', type_='unique')
    op.drop_index(op.f('ix_payroll_entries_period_key'), table_name='payroll_entries')
    op.create_unique_constraint(op.f('uq_schedule_employee'), 'payroll_entries', ['schedule_id', 'employee_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('payroll_entries', 'period_key')
    # ### end Alembic commands ###
