"""employee

Revision ID: dc7c1e3368c0
Revises: 478e1cbf39ac
Create Date: 2026-03-02 00:03:22.732454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7c1e3368c0'
down_revision: Union[str, Sequence[str], None] = '478e1cbf39ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_entries', sa.Column('employment_type', sa.String(), nullable=False))
    op.add_column('payroll_entries', sa.Column('annual_salary_snapshot', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('payroll_entries', sa.Column('hourly_rate_snapshot', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payroll_entries', sa.Column('federal_claim_snapshot', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('payroll_entries', sa.Column('ontario_claim_snapshot', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('payroll_entries', sa.Column('excluded', sa.Boolean(), nullable=False))
    op.alter_column('payroll_entries', 'regular_hours',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('payroll_entries', 'overtime_hours',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_column('payroll_entries', 'hourly_rate')
    op.drop_column('payroll_entries', 'overtime_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_entries', sa.Column('overtime_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('payroll_entries', sa.Column('hourly_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.alter_column('payroll_entries', 'overtime_hours',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('payroll_entries', 'regular_hours',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_column('payroll_entries', 'excluded')
    op.drop_column('payroll_entries', 'ontario_claim_snapshot')
    op.drop_column('payroll_entries', 'federal_claim_snapshot')
    op.drop_column('payroll_entries', 'hourly_rate_snapshot')
    op.drop_column('payroll_entries', 'annual_salary_snapshot')
    op.drop_column('payroll_entries', 'employment_type')
    # ### end Alembic commands ###
