"""add_invoice

Revision ID: dd0e7126f3eb
Revises: 2b5f2fc22bdb
Create Date: 2026-02-25 19:46:21.992871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0e7126f3eb'
down_revision: Union[str, Sequence[str], None] = '2b5f2fc22bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biz_entities', sa.Column('country', sa.String(length=20), nullable=True))
    op.alter_column('biz_entities', 'business_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('biz_entities', 'payroll_account_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('biz_entities', 'province',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.drop_column('users', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'country')
    op.alter_column('biz_entities', 'province',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
    op.alter_column('biz_entities', 'payroll_account_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('biz_entities', 'business_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.drop_column('biz_entities', 'country')
    # ### end Alembic commands ###
