"""payroll

Revision ID: ee55723c500d
Revises: c3599f7d7766
Create Date: 2026-02-16 21:43:26.535665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee55723c500d'
down_revision: Union[str, Sequence[str], None] = 'c3599f7d7766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_periods',
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_periods_id'), 'payroll_periods', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_periods_org_id'), 'payroll_periods', ['org_id'], unique=False)
    op.create_table('payroll_entries',
    sa.Column('payroll_period_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('regular_hours', sa.Float(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('overtime_hours', sa.Float(), nullable=False),
    sa.Column('overtime_rate', sa.Float(), nullable=False),
    sa.Column('bonus', sa.Float(), nullable=False),
    sa.Column('vacation', sa.Float(), nullable=False),
    sa.Column('gross', sa.Float(), nullable=False),
    sa.Column('cpp', sa.Float(), nullable=False),
    sa.Column('ei', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('net', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('b_int', sa.Integer(), nullable=True),
    sa.Column('b_str', sa.String(), nullable=True),
    sa.Column('b_decimal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('b_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('b_bool', sa.Boolean(), nullable=True),
    sa.Column('b_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_flag', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_entries_id'), 'payroll_entries', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_entries_org_id'), 'payroll_entries', ['org_id'], unique=False)
    op.add_column('cra_submissions', sa.Column('type', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('type', sa.String(), nullable=True))
    op.add_column('t4_records', sa.Column('type', sa.String(), nullable=True))
    op.alter_column('users', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('t4_records', 'type')
    op.drop_column('employees', 'type')
    op.drop_column('cra_submissions', 'type')
    op.drop_index(op.f('ix_payroll_entries_org_id'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_id'), table_name='payroll_entries')
    op.drop_table('payroll_entries')
    op.drop_index(op.f('ix_payroll_periods_org_id'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_id'), table_name='payroll_periods')
    op.drop_table('payroll_periods')
    # ### end Alembic commands ###
