"""payroll

Revision ID: ef595045803e
Revises: 3acde0fb9b24
Create Date: 2026-02-20 20:56:10.769348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef595045803e'
down_revision: Union[str, Sequence[str], None] = '3acde0fb9b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_users', sa.Column('avatar', sa.String(), nullable=True))
    op.drop_column('my_users', 'icon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_users', sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('my_users', 'avatar')
    # ### end Alembic commands ###
