"""add employee

Revision ID: f8f109aedbf4
Revises: aa6945b15d46
Create Date: 2026-03-17 12:39:15.209127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f109aedbf4'
down_revision: Union[str, Sequence[str], None] = 'aa6945b15d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_schedule_employee_period'), 'payroll_entries', type_='unique')
    op.alter_column('payroll_history', 'excluded',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payroll_history', 'excluded',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_unique_constraint(op.f('uq_schedule_employee_period'), 'payroll_entries', ['schedule_id', 'employee_id', 'period_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
