"""history

Revision ID: fa77642195b4
Revises: d90d2abd71ad
Create Date: 2026-03-13 23:00:04.197440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa77642195b4'
down_revision: Union[str, Sequence[str], None] = 'd90d2abd71ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payroll_entries', sa.Column('period_start', sa.Date(), nullable=True))
    op.add_column('payroll_entries', sa.Column('period_end', sa.Date(), nullable=True))
    op.create_index(op.f('ix_payroll_entries_period_end'), 'payroll_entries', ['period_end'], unique=False)
    op.create_index(op.f('ix_payroll_entries_period_start'), 'payroll_entries', ['period_start'], unique=False)
    op.alter_column('payroll_history', 'period_start',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('payroll_history', 'period_end',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payroll_history', 'period_end',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('payroll_history', 'period_start',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index(op.f('ix_payroll_entries_period_start'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_period_end'), table_name='payroll_entries')
    op.drop_column('payroll_entries', 'period_end')
    op.drop_column('payroll_entries', 'period_start')
    # ### end Alembic commands ###
