"""employee

Revision ID: fd101077e237
Revises: 8e0d60443dcb
Create Date: 2026-03-01 14:08:37.802573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd101077e237'
down_revision: Union[str, Sequence[str], None] = '8e0d60443dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('province', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('employment_type', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('employees', sa.Column('annual_salary', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('employees', sa.Column('federal_claim_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('employees', sa.Column('ontario_claim_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('employees', sa.Column('cpp_exempt', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('ei_exempt', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'ei_exempt')
    op.drop_column('employees', 'cpp_exempt')
    op.drop_column('employees', 'ontario_claim_amount')
    op.drop_column('employees', 'federal_claim_amount')
    op.drop_column('employees', 'annual_salary')
    op.drop_column('employees', 'hourly_rate')
    op.drop_column('employees', 'employment_type')
    op.drop_column('employees', 'end_date')
    op.drop_column('employees', 'start_date')
    op.drop_column('employees', 'province')
    op.drop_column('employees', 'date_of_birth')
    # ### end Alembic commands ###
